(function(g){var window=this;var rca=function(a,b){var c=[];g.An(b,function(a){try{var b=g.rr.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.r(b)?g.qr(b)&&c.push(a):c.push(a)},a);
return c},sca=function(a,b){var c=rca(a,b);
(0,g.G)(c,function(a){g.rr.prototype.remove.call(this,a)},a)},h7=function(a,b){g.BV.call(this,g.Q("YTP_MDX_TITLE"),0,a,b);
this.M=a;this.F={};this.O(a,"onMdxReceiversChange",this.J);this.O(a,"presentingplayerstatechange",this.J);this.J()},tca=function(){var a=g.nv;
sca(a,a.g.qe(!0))},i7=function(){this.g=[];
this.o=[]},j7=function(a){g.fw.call(this,"ScreenServiceProxy");
this.Zb=a;this.o=[];this.o.push(this.Zb.$_s("screenChange",(0,g.z)(this.kI,this)));this.o.push(this.Zb.$_s("onlineScreenChange",(0,g.z)(this.mF,this)))},k7=function(a){g.Rv("cloudview",a)},l7=function(a){k7("setApiReady_ "+a);
g.x("yt.mdx.remote.cloudview.apiReady_",a,void 0)},m7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},n7=function(a){g.Bu[a]&&(a=g.Bu[a],(0,g.G)(a,function(a){g.zu[a]&&delete g.zu[a]}),a.length=0)},o7=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},p7=function(){return g.y("yt.mdx.remote.connection_")},q7=function(a){g.x("yt.mdx.remote.connectData_",a,void 0)},r7=function(a){g.x("yt.mdx.remote.currentScreenId_",a,void 0)},B7=function(){return g.y("yt.mdx.remote.currentScreenId_")},
D7=function(){if(!C7){var a=g.y("yt.mdx.remote.screenService_");
C7=a?new j7(a):null}return C7},E7=function(a){g.x("yt.mdx.remote.cloudview.initializing_",a,void 0)},F7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},G7=function(a){k7("setCastInstalled_ "+a);
g.uv("yt-remote-cast-installed",a)},H7=function(a){g.Rv("cloudview",a)},uca=function(a,b){m7().init(a,b)},I7=function(){return!!g.vv("yt-remote-cast-installed")},K7=function(){k7("dispose");
var a=m7();a&&a.dispose();g.x("yt.mdx.remote.cloudview.instance_",null,void 0);l7(!1);g.Du(J7);J7.length=0},vca=function(){var a=window.document.createElement("a");
g.Wc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.eb(a)},wca=function(a,b){var c=g.Ed("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Xc(c,g.be("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},xca=function(a){var b=g.yu();
if(b)if(b.clear(a),a)n7(a);else for(var c in g.Bu)n7(c)},L7=function(){var a=o7();
a&&a(!1,"No cast extension found")},M7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},N7=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},yca=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},O7=function(){return g.y("yt.mdx.remote.channelParams_")||{}},Q7=function(a){var b=p7();
q7(null);a||r7("");g.x("yt.mdx.remote.connection_",a,void 0);P7&&((0,g.G)(P7,function(b){b(a)}),P7.length=0);
b&&!a?g.Fu("yt-remote-connection-change",!1):!b&&a&&g.Fu("yt-remote-connection-change",!0)},R7=function(){return g.y("yt.mdx.remote.connectData_")},S7=function(){var a=B7();
if(!a)return null;var b=D7().Vc();return g.ew(b,a)},T7=function(a,b){G7(!0);
E7(!1);uca(a,function(a){a?(l7(!0),g.Eu("yt-remote-cast2-api-ready")):(H7("Failed to initialize cast API."),G7(!1),g.wv("yt-remote-cast-available"),g.wv("yt-remote-cast-receiver"),K7());b(a)})},U7=function(){return I7()?m7()?m7().getCastSession():(H7("getCastSelector: Cast is not initialized."),null):(H7("getCastSelector: Cast API is not installed!"),null)},zca=function(){var a=vca(),b=window.document.getElementById(a),c=b&&g.Kt(b,"loaded");
c||b&&!c||(b=wca(a,function(){g.Kt(b,"loaded")||(g.Lt(b,"loaded","true"),g.Eu(a),g.Es(g.A(xca,a),0))}))},Aca=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},V7=function(){if(g.gY){var a=2,b=o7(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;N7("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",L7,c)}},W7=function(a){if(a>=g.jY.length)L7();
else{var b=g.jY[a],c="chrome-extension://"+b+g.fY;0<=g.hY.indexOf(b)?yca(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,N7(c,L7)):W7(a+1)}):N7(c,function(){W7(a+1)})}},Y7=function(a,b){B7();
S7()&&S7();r7(a.id);var c=new g.wx(X7,a,O7());c.connect(b,R7());c.subscribe("beforeDisconnect",function(a){g.Fu("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){p7()&&(p7(),Q7(null))});
Q7(c)},Z7=function(){var a=g.ow();
if(!a)return null;var b=D7().Vc();return g.ew(b,a)},$7=function(a){g.Rv("remote",a)},a8=function(){var a=p7();
return!!a&&3!=a.getProxyState()},b8=function(){F7()?m7().stopSession():H7("stopSession called before API ready.");
var a=p7();a&&(a.disconnect(1),Q7(null))},c8=function(){var a=D7().Zb.$_gos();
var b=S7();b&&p7()&&(g.dw(a,b)||a.push(b));return Aca(a)},f8=function(a,b){g.R.call(this);
this.g=0;this.B=a;this.D=[];this.C=new i7;this.A=this.o=null;this.J=(0,g.z)(this.ID,this);this.F=(0,g.z)(this.gi,this);this.H=(0,g.z)(this.HD,this);this.K=(0,g.z)(this.VD,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.xo,this),d8(this))):c=3;0!=c&&(b?this.xo(c):g.Es((0,g.z)(function(){this.xo(c)},this),0));
var d=U7();d&&e8(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},g8=function(a){return new g.kx(a.B.getPlayerContextData())},j8=function(a,b,c,d,e){var f=g8(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.ox(f,b,d);g.r(c)&&(g.mx(f,c),l.currentTime=c);g.r(k)&&(l.listId=k);h8(a,"setPlaylist",l);e||i8(a,f)},d8=function(a){(0,g.G)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.A(this.yF,a),this))},a)},k8=function(a){(0,g.G)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},l8=function(a,b){50>a.C.yd()&&a.C.o.push(b)},m8=function(a,b,c){var d=g8(a);
g.mx(d,c);-1E3!=d.g&&(d.g=b);i8(a,d)},h8=function(a,b,c){a.B.sendMessage(b,c)},i8=function(a,b){k8(a);
a.B.setPlayerContextData(g.px(b));d8(a)},e8=function(a,b){a.A&&(a.A.removeUpdateListener(a.J),a.A.removeMediaListener(a.F),a.gi(null));
a.A=b;a.A&&(n8("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.J),a.A.addMediaListener(a.F),a.A.media.length&&a.gi(a.A.media[0]))},o8=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=g8(a);b.contentId!=d.videoId&&n8("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.mx(d,a.o.getEstimatedTime());i8(a,d)}else n8("No cast media video. Ignoring state update.")},n8=function(a){g.Rv("CP",a)},p8=function(a,b,c){return(0,g.z)(function(a){this.xb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.xb("Retrying "+b+" using MDx browser channel."),h8(this,b,c))},a)},Bca=function(a,b,c){var d=!1;
m7()||(a=new g.ex(a,b,c),a.subscribe("yt-remote-cast2-availability-change",function(a){g.uv("yt-remote-cast-available",a);g.Fu("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){k7("onReceiverSelected: "+a.friendlyName);
g.uv("yt-remote-cast-receiver",a);g.Fu("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){k7("onReceiverResumed: "+a.friendlyName);
g.uv("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){k7("onSessionChange: "+g.aw(a));
a||g.wv("yt-remote-cast-receiver");g.Fu("yt-remote-cast2-session-change",a)}),g.x("yt.mdx.remote.cloudview.instance_",a,void 0),d=!0);
k7("cloudview.createSingleton_: "+d);return d},Cca=function(){var a=0<=g.Rb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.bt||a},q8=function(a,b){F7()?m7().setConnectedScreenStatus(a,b):H7("setConnectedScreenStatus called before ready.")},r8=function(){k7("clearCurrentReceiver");
g.wv("yt-remote-cast-receiver")},Dca=function(){if(M7("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){V7();a({command:"cast.sender.init"});return}}if(!window.chrome||M7("Edge"))L7();else if(V7(),M7("Android")&&M7("Chrome/")&&window.navigator.presentation){a="";var b=g.Sh();55<=b?a="55":50<=b&&(a="50");N7("//www.gstatic.com/eureka/clank"+a+g.fY,L7)}else W7(0)},Eca=function(a){a?(g.uv("yt-remote-session-app",a.app),g.uv("yt-remote-session-name",a.name)):(g.wv("yt-remote-session-app"),g.wv("yt-remote-session-name"));
g.x("yt.mdx.remote.channelParams_",a,void 0)},Fca=function(){var a=O7();
if(g.fc(a)){a=g.nw();var b=g.vv("yt-remote-session-name")||"",c=g.vv("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.x("yt.mdx.remote.channelParams_",a,void 0)}},Gca=function(){var a=Z7();
a?($7("Resume connection to: "+g.aw(a)),Y7(a,0)):(g.Aw(),r8(),$7("Skipping connecting because no session screen found."))},Hca=function(a){$7("remote.onCastSessionChange_: "+g.aw(a));
if(a){var b=S7();b&&b.id==a.id?q8(b.id,"YouTube TV"):(b&&b8(),Y7(a,1))}else p7()&&b8()},Ica=function(){var a=c8(),b=S7();
b||(b=Z7());return g.nb(a,function(a){return b&&g.Xv(b,a.key)?!0:!1})},s8=function(){var a=g.vv("yt-remote-cast-receiver");
return a?a.friendlyName:null},Jca=function(a,b,c,d,e,f){Cca()?Bca(b,e,f)&&(E7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?T7(a,c):(window.__onGCastApiAvailable=function(b,d){b?T7(a,c):(H7("Failed to load cast API: "+d),G7(!1),E7(!1),g.wv("yt-remote-cast-available"),g.wv("yt-remote-cast-receiver"),K7(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):zca():Dca())):k7("Cannot initialize because not running Chrome")},
t8=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Hg(a)||"";b&&(this.port=":"+b);this.domain=g.Gg(a)||"";a=g.Rb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.db(a,"10.0")&&(this.o=!1))},u8=function(){var a=Ica();
!a&&I7()&&s8()&&(a={key:"cast-selector-receiver",name:s8()});return a},Kca=function(){var a=c8();
I7()&&g.vv("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Lca=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.P("MDX_CONFIG")||b;g.nv&&tca();g.qw();X7||(X7=new t8(b?b.loungeApiHost:void 0),g.Cw()&&(X7.g="/api/loungedev"));P7||(P7=g.y("yt.mdx.remote.deferredProxies_")||[],g.x("yt.mdx.remote.deferredProxies_",P7,void 0));Fca();var c=D7();if(!c){var d=new g.Pw(X7);g.x("yt.mdx.remote.screenService_",d,void 0);c=D7();Jca(a,d,function(a){a?B7()&&q8(B7(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.Fu("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript),
b?b.appId:void 0,b?b.FL:!1)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.x("yt.mdx.remote.initialized_",!0,void 0),$7("Initializing: "+g.wg(b)),v8.push(g.Cu("yt-remote-cast2-availability-change",function(){g.Fu("yt-remote-receiver-availability-change")})),v8.push(g.Cu("yt-remote-cast2-receiver-selected",function(){q7(null);
g.Fu("yt-remote-auto-connect","cast-selector-receiver")})),v8.push(g.Cu("yt-remote-cast2-receiver-resumed",function(){g.Fu("yt-remote-receiver-resumed","cast-selector-receiver")})),v8.push(g.Cu("yt-remote-cast2-session-change",Hca)),v8.push(g.Cu("yt-remote-connection-change",function(a){a?q8(B7(),"YouTube TV"):Z7()||(q8(null,null),r8())})),a=O7(),b.isAuto&&(a.id+="#dial"),g.mt("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),$7(" -- with channel params: "+
g.wg(a)),Eca(a),c.start(),B7()||Gca())},w8=function(){I7()?m7()?F7()?(k7("Requesting cast selector."),m7().requestSession()):(k7("Wait for cast API to be ready to request the session."),J7.push(g.Cu("yt-remote-cast2-api-ready",w8))):H7("requestCastSelector: Cast is not initialized."):H7("requestCastSelector: Cast API is not installed!")},x8=function(a,b,c){g.I.call(this);
this.F=a;this.M=b;this.o=new g.iu(this);g.J(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.HE);this.o.O(b,"captionschanged",this.GD);this.o.O(b,"captionssettingschanged",this.ev);this.o.O(b,"videoplayerreset",this.ek);this.o.O(b,"mdxautoplaycancel",this.Ex);this.T=this.o.O(b,"onVolumeChange",this.Nt);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Vt,this);c.subscribe("remotePlayerChange",this.hi,this);c.subscribe("remoteQueueChange",this.ek,this);c.subscribe("autoplayUpNext",this.Dt,
this);c.subscribe("previousNextChange",this.St,this);c.subscribe("nowAutoplaying",this.Ot,this);c.subscribe("autoplayDismissed",this.Ct,this);this.suggestion=null;this.H=new g.OH(64);this.A=new g.O(this.av,500,this);g.J(this,this.A);this.B=new g.O(this.bv,1E3,this);g.J(this,this.B);this.C={};this.K=new g.O(this.xv,1E3,this);g.J(this,this.K);this.J=new g.ol(this.FB,1E3,this);g.J(this,this.J);this.N=g.va;this.ev();this.ek();this.hi()},y8=function(a,b){var c=a.F,d=a.M.getVideoData().lengthSeconds;
c.J=b||0;c.g.R("progresssync",b,d)},A8=function(a){y8(a,0);
a.A.stop();z8(a,new g.OH(64))},C8=function(a,b){if(B8(a)&&!a.D){var c=null;
b&&(c={style:a.M.Yf()},g.lc(c,b));a.g.Wu(a.M.getVideoData().videoId,c);a.C=g8(a.g).o}},D8=function(a,b){var c=a.M.ce();
c?j8(a.g,a.M.getVideoData().videoId,b,c.bb,c.listId.toString()):j8(a.g,a.M.getVideoData().videoId,b);z8(a,new g.OH(1))},E8=function(a,b){if(b){var c=a.M.Gb("captions","tracklist",{Tq:1});
c&&c.length?(a.M.zc("captions","track",b),a.D=!1):(a.M.Rh("captions"),a.D=!0)}else a.M.zc("captions","track",{})},B8=function(a){return g8(a.g).videoId==a.M.getVideoData().videoId},z8=function(a,b){a.B.stop();
var c=a.H;if(!g.UH(c,b)){var d=g.T(b,2);if(d!=g.T(a.H,2)){var e=a.M;g.SW(e.app,d,e.playerType)}a.H=b;F8(a.F,c,b)}},H8=function(a){g.X.call(this,{G:"div",
L:"ytp-remote",I:[{G:"div",L:"ytp-remote-display-status",I:[{G:"div",L:"ytp-remote-display-status-icon",I:[g.Yr()]},{G:"div",L:"ytp-remote-display-status-text",I:["{{statustext}}"]}]}]});this.o=new g.fR(this,250);g.J(this,this.o);this.A=a;this.O(a,"presentingplayerstatechange",this.B);G8(this,g.LN(a))},G8=function(a,b){if(3==a.A.Fa()){var c={RECEIVER_NAME:a.A.Gb("remote","currentReceiver").name};
c=g.T(b,128)?g.Q("YTP_MDX_STATUS_ERROR_2",c):b.sb()||g.T(b,4)?g.Q("YTP_MDX_STATUS_PLAYING_2",c):g.Q("YTP_MDX_STATUS_CONNECTED_2",c);a.ma("statustext",c);a.o.show()}else a.o.hide()},I8=function(a){g.cR.call(this,a);
this.A={key:g.cw(),name:g.Q("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.K=this.o=null;this.H=[this.A];this.B=this.A;this.F=new g.OH(64);this.J=0;var b=g.FN(a).F;b&&(b=b.A&&b.A.g)&&(b=new h7(a,b),g.J(this,b));b=new H8(a);g.J(this,b);g.gO(a,b.element,4)},F8=function(a,b,c){a.F=c;
a.g.R("presentingplayerstatechange",new g.ZH(c,b))},J8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)b8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData().videoId;if(c||d){var e=a.g.ce();if(e){var f=[];for(var k=0;k<e.getLength();k++)f[k]=e.wb(k).videoId}else f=[a.g.getVideoData().videoId];c={videoIds:f,listId:c,videoId:d,index:Math.max(a.g.Dr(),0),currentTime:a.g.getCurrentTime()}}else c=null;$7("Connecting to: "+g.wg(b));"cast-selector-receiver"==b.key?(q7(c||null),c=c||null,F7()?m7().setLaunchParams(c):H7("setLaunchParams called before ready.")):!c&&a8()&&B7()==b.key?g.Fu("yt-remote-connection-change",
!0):(b8(),q7(c||null),c=D7().Vc(),(c=g.ew(c,b.key))&&Y7(c,1))}};
g.p(h7,g.BV);h7.prototype.J=function(){var a=this.M.Gb("remote","receivers");a&&1<a.length&&!this.M.Gb("remote","quickCast")?(this.F=g.Nb(a,this.B,this),g.CV(this,(0,g.H)(a,this.B)),a=this.M.Gb("remote","currentReceiver"),this.Gd(this.B(a)),this.enable(!0)):this.enable(!1)};
h7.prototype.B=function(a){return a.key};
h7.prototype.Fd=function(a){return"cast-selector-receiver"==a?g.Q("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
h7.prototype.hc=function(a){g.BV.prototype.hc.call(this,a);this.M.zc("remote","currentReceiver",this.F[a]);this.A.ob()};
g.h=i7.prototype;g.h.yd=function(){return this.g.length+this.o.length};
g.h.isEmpty=function(){return g.sb(this.g)&&g.sb(this.o)};
g.h.clear=function(){this.g=[];this.o=[]};
g.h.contains=function(a){return g.rb(this.g,a)||g.rb(this.o,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.MX)(b,a);0<=c?(g.vb(b,c),b=!0):b=!1;return b||g.xb(this.o,a)};
g.h.Fb=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.o.length;for(b=0;b<c;++b)a.push(this.o[b]);return a};
g.E(j7,g.fw);g.h=j7.prototype;g.h.Vc=function(a){return this.Zb.$_gs(a)};
g.h.contains=function(a){return!!this.Zb.$_c(a)};
g.h.get=function(a){return this.Zb.$_g(a)};
g.h.start=function(){this.Zb.$_st()};
g.h.Mk=function(a,b,c){this.Zb.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Zb.$_r(a,b,c)};
g.h.Dk=function(a,b,c,d){this.Zb.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.o.length;a<b;++a)this.Zb.$_ubk(this.o[a]);this.o.length=0;this.Zb=null;j7.ga.W.call(this)};
g.h.kI=function(){this.R("screenChange")};
g.h.mF=function(){this.R("onlineScreenChange")};
var C7=null,J7=[],P7=null,X7=null;g.E(f8,g.R);g.h=f8.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.va,p8(this,"play")):h8(this,"play"),m8(this,1,g.nx(g8(this))),this.R("remotePlayerChange")):l8(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.va,p8(this,"pause")):h8(this,"pause"),m8(this,2,g.nx(g8(this))),this.R("remotePlayerChange")):l8(this,this.pause)};
g.h.Fv=function(a){if(1==this.g){if(this.o){var b=g8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;b.sb()||3==b.g?c.resumeState=window.chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.va,p8(this,"seekTo",{newTime:a}))}else h8(this,"seekTo",{newTime:a});m8(this,3,a);this.R("remotePlayerChange")}else l8(this,g.A(this.Fv,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.va,p8(this,"stopVideo")):h8(this,"stopVideo");var a=g8(this);a.index=-1;a.videoId="";g.lx(a);i8(this,a);this.R("remotePlayerChange")}else l8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=g8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){n8("set receiver volume: "+d)},this),(0,g.z)(function(){this.xb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){n8("set receiver muted: "+b)},this),(0,g.z)(function(){this.xb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);h8(this,"setVolume",e)}c.muted=b;c.volume=a;i8(this,c)}else l8(this,g.A(this.setVolume,a,b))};
g.h.Wu=function(a,b){if(1==this.g){var c=g8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.wg(b.style),g.lc(d,c.o));h8(this,"setSubtitlesTrack",d);i8(this,c)}else l8(this,g.A(this.Wu,a,b))};
g.h.wo=function(a,b){if(1==this.g){h8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Sb.id});var c=g8(this);c.audioTrackId=b.Sb.id;i8(this,c)}else l8(this,g.A(this.wo,a,b))};
g.h.Ev=function(a,b){if(1==this.g){if(a&&b){var c=g8(this);g.ox(c,a,b);i8(this,c)}h8(this,"previous")}else l8(this,g.A(this.Ev,a,b))};
g.h.Dv=function(a,b){if(1==this.g){if(a&&b){var c=g8(this);g.ox(c,a,b);i8(this,c)}h8(this,"next")}else l8(this,g.A(this.Dv,a,b))};
g.h.Zp=function(){1==this.g?h8(this,"dismissAutoplay"):l8(this,this.Zp)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.R("proxyStateChange",a,this.g)}f8.ga.dispose.call(this)};
g.h.W=function(){k8(this);this.B=null;this.C.clear();e8(this,null);f8.ga.W.call(this)};
g.h.xo=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.sb(b.g)&&(b.g=b.o,b.g.reverse(),b.o=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.yF=function(a,b){this.R(a,b)};
g.h.ID=function(a){if(!a)this.gi(null),e8(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=g8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)n8("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,i8(this,b)}};
g.h.gi=function(a){n8("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.H);if(this.o=a)this.o.addUpdateListener(this.H),o8(this),this.R("remotePlayerChange")};
g.h.HD=function(a){a?(o8(this),this.R("remotePlayerChange")):this.gi(null)};
g.h.VD=function(){var a=U7();a&&e8(this,a)};
g.h.xb=function(a){g.Rv("CP",a)};
var v8=[];g.h=t8.prototype;g.h.Nf=function(a){var b=this.g;if(g.r(void 0)?0:this.o)b="https://"+this.domain+this.port+this.g;return g.Rg(b+a,{})};
g.h.vo=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,rb:g.A(this.fI,c,!0),onError:g.A(this.eI,d),Oc:g.A(this.gI,d)};b&&(c.kb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Us(a,c)};
g.h.fI=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.eI=function(a,b){a(Error("Request error: "+b.status))};
g.h.gI=function(a){a(Error("request timed out"))};g.p(x8,g.I);g.h=x8.prototype;g.h.W=function(){g.I.prototype.W.call(this);this.A.stop();this.B.stop();this.N();this.g.unsubscribe("proxyStateChange",this.Vt,this);this.g.unsubscribe("remotePlayerChange",this.hi,this);this.g.unsubscribe("remoteQueueChange",this.ek,this);this.g.unsubscribe("autoplayUpNext",this.Dt,this);this.g.unsubscribe("previousNextChange",this.St,this);this.g.unsubscribe("nowAutoplaying",this.Ot,this);this.g.unsubscribe("autoplayDismissed",this.Ct,this);this.g=this.F=null};
g.h.hs=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(B8(this)){if(1081!=g8(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":g8(this.g).sb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.J.Ag(c[0],c[1]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.g.wo(this.M.getVideoData().videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":D8(this,this.M.getCurrentTime());break;case "control_seek":D8(this,c[0]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.g.wo(this.M.getVideoData().videoId,c)}};
g.h.GD=function(a){this.hs("control_subtitles_set_track",g.fc(a)?null:a)};
g.h.ev=function(){var a=this.M.Gb("captions","track");g.fc(a)||C8(this,a)};
g.h.Nt=function(a){if(B8(this)){this.g.unsubscribe("remotePlayerChange",this.hi,this);var b=Math.round(a.volume);a=!!a.muted;var c=g8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.hi,this)}};
g.h.HE=function(){g.fc(this.C)||E8(this,this.C);this.D=!1};
g.h.Vt=function(a,b){this.B.stop();2==b&&this.bv()};
g.h.hi=function(){if(B8(this)){this.A.stop();var a=g8(this.g);switch(a.g){case 1081:z8(this,new g.OH(8));break;case 1:this.av();z8(this,new g.OH(8));break;case 1083:case 3:z8(this,new g.OH(9));break;case 0:z8(this,new g.OH(2));this.J.stop();y8(this,this.M.getVideoData().lengthSeconds);break;case 1082:z8(this,new g.OH(4));break;case 2:z8(this,new g.OH(4));y8(this,g.nx(a));break;case -1:z8(this,new g.OH(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.Q("YTP_MDX_PLAYER_ERROR")},z8(this,
new g.OH(128,a))}a=g8(this.g).o;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,E8(this,a));a=g8(this.g);-1==a.volume||Math.round(this.M.getVolume())==a.volume&&this.M.yc()==a.muted||this.K.isActive()||this.xv()}else A8(this)};
g.h.St=function(){this.M.R("mdxpreviousnextchange")};
g.h.ek=function(){B8(this)||A8(this)};
g.h.Ex=function(){this.g.Zp()};
g.h.Dt=function(a){a&&(a=g.Us("/watch_queue_ajax",{method:"GET",Wb:{action_get_watch_queue_item:1,video_id:a},rb:(0,g.z)(this.tG,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.tG=function(a,b){var c=new g.uG({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.M.R("mdxautoplayupnext",c)};
g.h.Ot=function(a){(0,window.isNaN)(a)||this.M.R("mdxnowautoplaying",a)};
g.h.Ct=function(){this.M.R("mdxautoplaycanceled")};
g.h.FB=function(a,b){-1==g8(this.g).g?D8(this,a):b&&this.g.Fv(a)};
g.h.xv=function(){if(B8(this)){var a=g8(this.g);this.o.Ma(this.T);a.muted?this.M.mute():this.M.ee();this.M.setVolume(a.volume);this.T=this.o.O(this.M,"onVolumeChange",this.Nt)}};
g.h.av=function(){this.A.stop();if(!this.g.fa()){var a=g8(this.g);a.sb()&&z8(this,new g.OH(8));y8(this,g.nx(a));this.A.start()}};
g.h.bv=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(H8,g.X);H8.prototype.B=function(a){G8(this,a.state)};g.p(I8,g.cR);g.h=I8.prototype;g.h.create=function(){Lca(g.mE(g.V(this.g)));this.D.push(g.Cu("yt-remote-before-disconnect",this.ED,this));this.D.push(g.Cu("yt-remote-connection-change",this.HF,this));this.D.push(g.Cu("yt-remote-receiver-availability-change",this.Tt,this));this.D.push(g.Cu("yt-remote-auto-connect",this.FF,this));this.D.push(g.Cu("yt-remote-receiver-resumed",this.EF,this));this.Tt()};
g.h.load=function(){this.g.yl();g.cR.prototype.load.call(this);this.C=new x8(this,this.g,this.o);var a=R7();a=a?a.currentTime:0;var b=a8()?new f8(p7(),void 0):null;0==a&&b&&(a=g.nx(g8(b)));0!=a&&(this.J=a||0,this.g.R("progresssync",a,void 0));F8(this,this.F,this.F);g.YW(this.g.app,6)};
g.h.unload=function(){this.g.R("mdxautoplaycanceled");this.B=this.A;g.Le(this.C,this.o);this.o=this.C=null;g.cR.prototype.unload.call(this);g.YW(this.g.app,5)};
g.h.W=function(){g.Du(this.D);g.cR.prototype.W.call(this)};
g.h.Xh=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.hs.apply(this.C,[].concat([a],g.oa(c)))};
g.h.hy=function(){return this.loaded?this.C.suggestion:null};
g.h.Yd=function(){return this.o?g8(this.o).Yd:!1};
g.h.hasNext=function(){return this.o?g8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.iB=function(){var a=g8(this.o),b=this.g.getVideoData();return{allowSeeking:this.g.Kc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+((0,g.F)()-a.A)/1E3:a.C,isPeggedToLive:1>=(a.F?a.B+((0,g.F)()-a.A)/1E3:a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+((0,g.F)()-a.A)/1E3:a.B,seekableStart:0<a.D?a.D+((0,g.F)()-a.A)/1E3:a.D}};
g.h.jB=function(){this.o&&this.o.Dv()};
g.h.kB=function(){this.o&&this.o.Ev()};
g.h.ED=function(a){1==a&&(this.K=this.o?g8(this.o):null)};
g.h.HF=function(){var a=a8()?new f8(p7(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Ke(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.g.getVideoData().videoId&&this.g.Br(a.videoId,g.nx(a)));this.g.R("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.Tt=function(){this.H=[this.A].concat(Kca());var a=u8()||this.A;J8(this,a);this.g.ua("onMdxReceiversChange")};
g.h.FF=function(){var a=u8();J8(this,a)};
g.h.EF=function(){this.B=u8()};
g.h.hB=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?w8():J8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&w8(),!0):!1}};
g.h.lB=function(){h8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ac=function(){return!1};g.FR("remote",I8);})(_yt_player);
